services:
  web:
    build: ./web   # 從 Dockerfile build
    container_name: demo8-web
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
    depends_on:
      - cache

  cache:  # Service 名稱 = hostname
    image: redis:7-alpine
    container_name: demo8-cache # 容器名(CLI 用)
    volumes:
      - redis-data:/data

volumes:
  redis-data:
